version: '3'
services:
    php:
        image: webdevops/php-nginx-dev:7.3
        container_name: ecommerce-server
        working_dir: /app
        restart: always
        environment:
            - WEB_DOCUMENT_ROOT=/app
            - PHP_DISPLAY_ERRORS=true
            - XDEBUG_START_WITH_REQUEST=yes
        ports:
            - "80:80"
        volumes:
            - ./:/app:rw,cached
            # - ./.docker/site.conf:/opt/docker/etc/nginx/conf.d/site.conf
        depends_on:
            - mysql

    mysql:
        image: mariadb:10.8.2
        container_name: ecommerce-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_ecommerce
        ports:
            - "3306:3306"
        command:
            'mysqld --default-authentication-plugin=mysql_native_password --innodb-flush-method=fsync --innodb-use-native-aio=0'
        volumes:
            - ./.docker/data/mysql/db:/var/lib/mysql